### ISSUE TITLE
Criação de activity da tela inicial do jogo

### ISSUE THREAD

**Issue by jackson-roberio** [jackson-roberio/JacKar-Android#1]
Atualmente todo o código está voltando para o JS, tendo hoje apenas uma WebView que exibe as três telas do jogo, a intenção é que algumas telas telas saiam do JS e venham para Android, sendo necessário assim criar Activitys dessas telas e linkalas para os as outras páginas ou para própria WebView (que não enfrentará modificação).

Tela:

<img src="https://github.com/jackson-roberio/JacKar-Android/raw/main/material-de-apoio/captura-de-tela/tela_inicial.png" height="300" />

O desenvolvedor pode ficar à vontade por trazer uma solução viável para tela acima nos moldes de uma Activity, alguns materiais de design's podem ser encontrados em: https://github.com/jackson-roberio/JacKar-Android/tree/main/material-de-apoio/imagens

**Por favor, antes de começar a desenvolver a solução, sinalizar que tem interesse nessa issue comentando nela e aguardando o ok (meu) do desenvolvedor para realização da solução.**

**Comment by everton4292** [comment]
Opa, vou fazer essas telas

**Comment by jackson-roberio** [comment]
> Opa, vou fazer essas telas

Associado essa tarefa à você Everton, qualquer dúvida ou ajuda pode me contatar.
