### ISSUE TITLE
Criação de activity da tela Crédito do jogo

### ISSUE THREAD

**Issue by jackson-roberio** [jackson-roberio/JacKar-Android#2]
Atualmente todo o código está voltando para o JS, tendo hoje apenas uma WebView que exibe as três telas do jogo, a intenção é que algumas telas telas saiam do JS e venham para Android, sendo necessário assim criar Activitys dessas telas e linkalas para os as outras páginas ou para própria WebView (que não enfrentará modificação).

Tela:
<img src="https://github.com/jackson-roberio/JacKar-Android/blob/main/material-de-apoio/captura-de-tela/tela_creditos.png?raw=true" height="300" />

O desenvolvedor pode ficar à vontade por trazer uma solução viável para tela acima nos moldes de uma Activity, alguns materiais de design's podem ser encontrados em: https://github.com/jackson-roberio/JacKar-Android/tree/main/material-de-apoio/imagens

Está tela poderá ou melhor, deverá ser totalmente alterada, podendo o colaborador fazer uma solução com um design mais elegante sem problema, aceitarei o seu pull request, deixe espaço para inserção dos dois colaboradores adicionais.

Links da página:

**Politica de privacidade** = https://jacksonroberio.com.br/jackar/politica-privacidade/politica-privacidade.pdf

**Jackson Roberio** = https://jacksonroberio.com.br

**Design** = https://www.flaticon.com

**Áudio** = https://freesound.org

**Voltar** = *este link depende da Activity produzida na issue* #1 , porém, o desenvolvedor pode deixar sem linkamento nenhum, se conseguir realizar a tarefa antes da entrega da issue #1 .

Por favor, antes de começar a desenvolver a solução, sinalizar que tem interesse nessa issue comentando nela e aguardando o ok (meu) do desenvolvedor para realização da solução.

**Comment by everton4292** [comment]
Opa Jackson, vou procurar fazer essa aqui também

**Comment by jackson-roberio** [comment]
> Opa Jackson, vou procurar fazer essa aqui também

Obrigado @everton4292 , associado a você.
